### ISSUE TITLE
Windows file names can't contain `:`

### ISSUE THREAD

**Issue by joachimvh** [eyereasoner/rdfsurfaces-tests#1]
It is impossible to check out this repository as it contains files with characters that are [not allowed](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions) on Windows. Specifically the `:` should be replaced with another character, perhaps `$`?

**Comment by phochste** [comment]
Should be fixed now

**Comment by joachimvh** [comment]
Thanks!
