### ISSUE TITLE
Making tests work on Windows

### ISSUE THREAD

**Issue by joachimvh** [eyereasoner/rdfsurfaces-tests#3]
Besides https://github.com/eyereasoner/rdfsurfaces-tests/pull/2 there were some other changes I had to do. I specifically had to change `timeout 10s $HOME/github.com/joachimvh/tension.js/bin/tension.js` in the example config to `node $HOME/github.com/joachimvh/tension.js/bin/tension.js` as the windows timeout command works differently, and it also doesn't recognize the hashbang syntax to run the file. The problem with doing this is that after the tests are finished running, the node processes don't stop, which is why I didn't add this change to the PR.

**Comment by phochste** [comment]
Yes, this timeout issue is quite annoying. I did several attempts to solve this within node, but didn't find a portable solution yet.
Maybe for now you can contribute an example how the config file timeout should look like for windows and we could provide config for the varios OS-es.
